databases:
  - name: postgres
    ipAllowlist:
     -0.0.0.0/0

services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_MASTER_KEY
        fromDatabase:
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    ipAllowList:
      -0.0.0.0/0
    plan: free
    maxmemoryPolicy: noeviction
