databases:
  - name: cash_flow
    databaseName: cash_flow
    user: cash_flow_user

services:
  - type: web
    name: cash_flow_nexus
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cash_flow
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
